travis:
  secure:
    BINSTAR_TOKEN: C8/ZYctnW6WucrnxRT7SV/Cly+jbcBS4LfOBgglMQdgkj0r09USbDf+BGiCSeFj7QcrWTupWStJFsTBZJGLlyW6lZAGMjVtZWp+cZS4Iz7+Q44moDzt5bzW0s/iQyXaOvQV+1BsHZ2xPVTzCAaU1pNE7ClGd9S79bvl9Eihj55eyGJATFDPrN4T8mlTDVQEdOPXujAGcCrAWW2NT4d/9zE0J85toKtFlWQpYtLD6luP1VXf8ISJkLWKAn60mOsUoiiMty8UMFj/6ZY+3M8TdCwmRT2Sj/iLFt0zxz7CkOhqyhDX8pdWJaJNGsrE7HyCO8MM15u8xYbq4m5DhKbiTE8/I7pi224bWdMumUajoZzJ5Dm7WgCOqugKtsOElQ99Hb/kFOJV+7R4hrnuWzI0FGI1ECLypzngqE0/AHqyPnNcOMY915i90FWAIxCVwpy7JdaeBp7zQT9xgEwmn6B9v8fVnp50eBbOTSkULn4pKLqPQhkx5DOFbWTNyKO/jwVMwHEShgP8elLRLwhQ7SLYl01q4ZqLHhWo5QOHU5Piqk7bg+cAuIVm/fhU1ij/MFZlzNzAcxdfw4smRg7HxkUgxq6CqUta6ypxfWqiQVjn9jLvrHTpSiEcW2nsBtO63duLE0YG4o+vtZjAd8FmcLWyTf9SB2PA0ya0OTyilRUYwUng=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
