travis:
  secure:
    BINSTAR_TOKEN: XojNukEeKZEw9Uh11xT8vY/esD376oGSOUHnyB08VHbwbpY2LTTCNaPuU4BZiYrIYRtR2KnW08CGjTIwLU1HI70NJROclhEV2458WtSaJ8TTs0M7My8imGhi9srwDL5NrklHnSW78jGqUmzRUt36C0TAp7cI+RLYdvc5NgdVAsyYhstWXa5X19CsRKySRqYYMFLA0hKr6cdj1yeCradJcLsddnbec39BkiBiHwwFyLP8sL5q0lG+66iMr9LaPPqmXeskBKUQhItMzmdrYDlok2Af7vimZ0Ip7dbHqJJPublRj67XlcLLpJ+OEADcTiPwTSrEcuSRWyZHUJfXGMJTRhVP1Hy8cI0RF+zZEunGDULHeyth1p2PfcPzECSlNL7WNWpUgqeDqtOI7BT+IEyrZwXIPI59WyMv+s/+e7qJgkPbsNPpfEjrkk1J9NTNvYNPR6iR+1VNTBqigGc6w4XxbjcPTGqOkqo/saudEdrlY85WzqETcNH1izCZ2SllJwYvQL8IYMpqPp0vUXwRi2PXGCKRx2gt6UuPUndeVyvRPaCgv2lmo8t94gY+aYyCvoR9NnhwHNlmh356TySYxKipj7FdAoDyoxSLzqrcMSLwebKHldOxrFspBCUhp8XuGCUcxbShEWEvOG7ZOYihDAPLyAhXw8PFJqbAIY+ENVIq9xQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
